apiVersion: apps/v1
kind: Deployment
metadata:
  name:  publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template: 
    metadata:
      labels:
        app: publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "publisher"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: publisher
        image: ocimar/quarkus-publisher
        ports:
        - containerPort: 8080