apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://user:password@rabbitmq.default.svc.cluster.local:5672" # local: "amqp://localhost:5672"
