apiVersion: apps/v1
kind: Deployment
metadata:
  name:  subscriber-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber-two
  template: 
    metadata:
      labels:
        app: subscriber-two
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subscriber-two"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: subscriber-two
        image: ocimar/subscriber-two
        ports:
        - containerPort: 8080